services:
  - type: web
    name: winetasting-app
    env: node
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_TYPE
        value: sqlite
      - key: DB_PATH
        value: ./database/wine_tasting.db
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CORS_ORIGIN
        value: https://winetasting.uno
      - key: FRONTEND_URL
        value: https://winetasting.uno
      - key: SEND_REAL_EMAILS
        value: true
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        value: gilbert.regent@gmail.com
      - key: SMTP_PASS
        value: gfqy knkq sokd whxp

  - type: static
    name: winetasting-frontend
    buildCommand: "echo 'No build needed for static files'"
    staticPublishPath: ./web-version
    routes:
      - type: rewrite
        source: /api/*
        destination: https://winetasting-app.onrender.com/*